### ISSUE TITLE
GXV3370 not extract firmware

### ISSUE THREAD

**Issue by EygenyZaicev** [danry25/HT802#4]
Hi, i have a problem to extract firmware gxv3370, i dont know to fix thix. Maybe you have a idea for fix thix?)(logs from logcat and nginx)
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: Version: 0.1 Compiled on Feb 25 2022, 19:59:08
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: Firmware Upgrade Via: HTTP
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: Firmware Path: http://host.com/gxv3370fw.bin
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: Incremental Upgrade:Yes
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: mkfifo </tmp/fwdetect.fifo>
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: seek end relocation 96 --> 1024
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: signature: 0x43a78f39
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: old kernel 1.0.1.30
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: seek end relocation 160 --> 1120
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: new kernel 1.0.1.30
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: signature  oem_id hw_id   fw_vmask idt_len seg_id date     version size/size_used name
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: 0x43a78f39 0x0000 0x0051 0x0000   0x0000 0xfe02 0x6332a784 1.0.1.30 0x0092ed00/0x92eb00 kernel
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: supported_bits
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: 0x0000.0x0000.0x0000.0x00ff
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: The same version and size_used
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: old recovery 1.0.1.12
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: new recovery 1.0.1.12
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: signature  oem_id hw_id   fw_vmask idt_len seg_id date     version size/size_used name
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: 0x43a78f39 0x0000 0x0051 0x0000   0x0000 0xfe08 0x6332a784 1.0.1.12 0x00b52500/0xb52300 recovery
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: supported_bits
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: 0x0000.0x0000.0x0000.0x00ff
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: The same version and size_used
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: old system 1.0.3.46
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: new system 1.0.3.46
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: signature  oem_id hw_id   fw_vmask idt_len seg_id date     version size/size_used name
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: 0x43a78f39 0x0000 0x0051 0x0000   0x40100 0xfe04 0x6332a784 1.0.3.46 0x261b973d/0x261b953d system
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: supported_bits
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: 0x0000.0x0000.0x0000.0x00ff
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: The same version and size_used
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: All the SEGs with the same version, continue check image header
Jan 31 04:05:17 localhost <14> GXV3370 [C0:74:AD:54:9A:0C]: prov_detect: Report version Same

192.168.69.36 - - [05/Feb/2023:09:42:53 +0300] "GET /gxv3370fw.bin HTTP/1.1" 206 1024 "-" "Grandstream Model HW GXV3370>192.168.69.36 - - [05/Feb/2023:09:42:53 +0300] "GET /gxv3370fw.bin HTTP/1.1" 206 1024 "-" "Grandstream Model HW GXV3370>192.168.69.36 - - [05/Feb/2023:09:42:53 +0300] "GET /gxv3370fw.bin HTTP/1.1" 206 1024 "-" "Grandstream Model HW GXV3370>192.168.69.36 - - [05/Feb/2023:09:42:53 +0300] "GET /gxv3370fw.bin HTTP/1.1" 206 64 "-" "Grandstream Model HW GXV3370  >192.168.69.36 - - [05/Feb/2023:09:42:53 +0300] "GET /gxv3370fw.bin HTTP/1.1" 206 64 "-" "Grandstream

**Comment by danry25** [comment]
Your new firmware and current firmware are the same version. This repo isn't for any GXV series phones, closing issue,
