### ISSUE TITLE
Emulation with Qemu

### ISSUE THREAD

**Issue by mgaloi** [danry25/HT802#5]
Hi,
I would like to emulate the Grandstream HT802 firmware using Qemu. Do you have any idea how to do it step by step?
thanks

**Comment by danry25** [comment]
This isn't a complete, bootable image, but there are others here on Github if I recall.

**Comment by mgaloi** [comment]
I tried with the image provided by BigNerd95 but I'm stuck when running the script /etc/rc.d/rc.service. it's not recognizing the nvram command.
